### ISSUE TITLE
کاری که شد نداره 

### ISSUE THREAD

**Issue by amirpm2050** [miladheydari/MiladBadgeView#1]
میلاد من میخوام اون ماست ماسک دوره ایکون بچرخه انقد که کاربر سر گیجه بگیره دوست دارم سرعتش به سرعت سانتریفیوژ نزدیک شه تا کاربر دار فانی و وداع بگه

**Comment by miladheydari** [comment]
@amirpm2050  هههممم فکر خوبیه بهش فک میکنم ریلیز میدم بعدا

**Comment by amirpm2050** [comment]
eyval dari ke
